spring.application.name=portfolio_generator
spring.datasource.name=portfolio
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio
spring.datasource.username=mayur
spring.datasource.password=sv11rk20@75#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf

server.address=0.0.0.0
server.port=8080

#spring email config 
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=2481c4d6270e1f
spring.mail.password=e189cacb8f0add
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
